# Generated by Django 4.1.3 on 2022-12-02 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_listing_bid_bids_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='listing',
            new_name='listin',
        ),
    ]
