# Generated by Django 4.1.3 on 2022-12-02 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='listin',
        ),
    ]
