# Generated by Django 4.1.3 on 2022-12-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(related_name='wl', to='auctions.listing'),
        ),
        migrations.DeleteModel(
            name='watchList',
        ),
    ]
